title: System Programing - Pemerograman Sistem
version:     "087 --- 23-May-2024"
copyright:   "2021-2024"
description: This is the System Programing course site,
      a GitHub Page, hosted at GitHub.com (thank you!).
      This site contains links to lecture materials, exam questions, and laboratory materials.
      It is based on "Google Here, Google There, Try This, Try That, and then Ask Anybody (GHGTT4A2)".
disc: You are free to share, copy and redistribute the material of this site 
      in any medium or format for any purpose, even commercially. 
      Please give appropriate credit, provide a link to the page, 
      and indicate if changes were made. You may do so in any reasonable manner. 
      You should not apply legal terms or technological measures, 
      that legally restrict others from doing anything that is permitted here.
author: C. BinKadal
google_analytics: G-BL9D1PZCHY
address: "Sendirian, Berhad."
sitemap: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://sp.vlsm.org/"
urlscele:         "https://scele.cs.ui.ac.id/course/view.php?id=3742"
urllogcode:       "https://doit.vlsm.org/ETC/logCodes.txt"
urlcontact:       "TBA"
urlgithub:        "https://github.com/os2xx/sysprog/"
urlghpage:        "https://sp.vlsm.org/"
keywords:         "jekyll, testing"
github:           [metadata]

